### ISSUE TITLE
Command TOPIC

### ISSUE THREAD

**Issue by Laendrun** [Laendrun/ft_irc#15]

**Comment by blaisek** [comment]
/topic #channel newtopic, Changes the topic for a channel that you are on if you're an operator. and /topic to view the topic inside the channel

**Comment by Laendrun** [comment]
anyone in the channel should be able to set the topic when the mode T is disabled
And if the mode T is enabled, only the chanops can set the topic
You can easily check if the mode is set or not by calling the following function :
```c++
bool Channel::getMode(char mode) const;

channel->getMode('t');
```

**Comment by blaisek** [comment]
commit 7d01a76b09c76d6f4aff91062110eb25cb982f94
