### ISSUE TITLE
Channels can have more than one mode

### ISSUE THREAD

**Issue by Laendrun** [Laendrun/ft_irc#17]
@blaisek in your current implementation of the channel class, it only supports one mode but a channel, as a user could have multiple modes.

For now I'll create new functions that returns a sample value in the format that I need for use with the commands.

**Comment by blaisek** [comment]
yes, the channel class need some modes as attributes and new functions to modify their states

**Comment by blaisek** [comment]
@Laendrun  I see. I'll add a method to add modes and a method to find and remove them from the string. I'll push the commit with the join cmd.
