### ISSUE TITLE
Command PART

### ISSUE THREAD

**Issue by blaisek** [Laendrun/ft_irc#21]
The /part command is used when you want to depart/leave a specific channel, or the current active channel. This command also allows you to specify a parting message, which will display to the remaining users a custom message in the server's PART message.

**Comment by blaisek** [comment]
/part closes the window but "channel not found" error in sendMessageToChannelUsers after sending a broadcast message. segfault at /quit: removeClient and irssi: critical sig_message_join: assertion 'nick != NULL' failed

**Comment by blaisek** [comment]
ready to merge, but still have 2 assertions that failed

commit: b29304e52f

**Comment by blaisek** [comment]
ready to merge, but still have 2 assertions that failed

commit: b29304e52f99cfc0a08888cbb3dc7bc67eba5012

**Comment by Laendrun** [comment]
I'll merge it later when I get home and take a look at the assertions
maybe I can find what response is missing for these assertions
