### ISSUE TITLE
Server crash when wrong password given

### ISSUE THREAD

**Issue by Laendrun** [Laendrun/ft_irc#22]
If we enter a wrong password when we try to login, irssi thinks we are connected to the server, the problem is that we are not really

when we then try to join a channel, the server crashes because it tries to access a client that is not really a client...

**Comment by Laendrun** [comment]
Okay so the problem is really coming from the channel, trying to connect with a wrong password / no password, then the server does not crash
But then when I join a channel, the server crash when using /QUIT, and I think it's related to #23

**Comment by blaisek** [comment]
yeah, and I've come to the conclusion that it's probably also related to #21 and the part command not closing the channel window
