### ISSUE TITLE
Server crash when the last client leave

### ISSUE THREAD

**Issue by blaisek** [Laendrun/ft_irc#23]
SegFault with the "QUIT" command

**Comment by Laendrun** [comment]
the server crashes only when the clients using the QUIT command are in a channel
I tried to connect 2 clients to the server without joining any channels and the server didn't crash when both of them used /QUIT
Then I did the same thing but I joined the same channel with both clients, and when the second client used /QUIT, the server crashed
I also tried joining two different channels and when the last client used /QUIT, the server crashed

I think the crashed is caused somewhere in the channels but not quite sure where exactly

**Comment by blaisek** [comment]
Alright, so we need to redefine how we create and leave a channel
