### ISSUE TITLE
Think about modes and how to implement them

### ISSUE THREAD

**Issue by Laendrun** [Laendrun/ft_irc#8]
There are two types of _MODES_ : user modes and channel modes. Some of them work the same but not all of them.

**Comment by blaisek** [comment]
there is nothing specific about modes in the project statement. depending on the document below, there may be a lot of options. which ones do we want to implement?

https://fr.wikibooks.org/wiki/Guide_d%27utilisation_de_l%27IRC/Index_des_modes_et_commandes

**Comment by Laendrun** [comment]
I think we'll use the "basics" ones from the original IRC RFC [rfc-editor.org](https://www.rfc-editor.org/rfc/rfc1459#section-4.2.3.1)
